### ISSUE TITLE
Suggestion for array field types

### ISSUE THREAD

**Issue by kokosro** [kostafey/clucy#2]
Hey,

In clucy.core I would suggest to update the creation of docs from maps to accommodate arrays of values as well, something like the following. 

``` clojure
(defn doc->map [doc]
  (let [fields (.getFields doc)]
    (reduce (fn [the-map field]
              (let [field-name (keyword (.name field))
                    field-value (.stringValue field)]
                (if (contains? the-map field-name)
                  (assoc the-map field-name (into [] (flatten (concat [(get the-map field-name)] [field-value]))))
                  (assoc the-map field-name field-value)))) {} fields)))


(defn map->doc [the-map]
  (reduce (fn [the-doc [field-key field-value]]
                     (if (vector? field-value)
                       (doall (map (fn [a-val]
                                     (add-field the-doc (as-str field-key) a-val)) field-value))
                       (add-field the-doc (as-str field-key) field-value))
                     the-doc) (Document.) the-map))


(def doc-from-a-map (map->doc {:values ["something" "something else" "yet another thing" "just some value in an array of values"]
                               :single "one value"}))
```

This could be extended to nested maps as well,

``` clojure
(def nested-map {:book {:author {:name "Salinger, J.D."}
                                       :title "Nine Stories"}})
```

would create a document with the following field names

book.author.name
book.title

**Comment by kokosro** [comment]
Here is the commit that enables clucy to accept array as field value

https://github.com/kokosro/clucy/commit/bbbbc81836556bafb059d22d45445d82f4fcb17b

**Comment by kostafey** [comment]
Hi!

I think I've got your idea but there are bunch of questions.
- If you are going to prepare pull request please try to be silent in your diff. There are different whitespaces in yor commit for the whole file, so it's harder to read. If you disagree with whitespaces, please do it in separate commit, e.g. "Fix whitespaces", but it's an other story, old whitespaces are ok. Furthermore reduce the length of code lines to 80 characters.
- Write docstrings.
- I think it's harder to read

``` clojure
(into [] (flatten (concat [(get the-map field-name)] [field-value])))
```

than more straightforward

``` clojure
(let [existing-value (get the-map field-name)]
  (if (vector? existing-value)
    (into [field-value] existing-value)
    [field-value existing-value]))
```
- Existance of both `doc->map` and `document->map` functions is inadmissible (the same story with `map->document` and `map->doc`). It'll confuse people. So, please try to integrate your code into existing functions (via additional optional arguments or lexical binding values).
- Vectors is just one of special cases, it will be better to generalize it if it's possible.
- Write tests.

**Comment by kokosro** [comment]
Hi,
I have reverted the whitespace mess and recommitted the changes with a test  for the array fields indexing.

https://github.com/kokosro/clucy/commit/11abc9580bfbce593c718f647b5baaf1d45664fb

Please have a look

**Comment by kokosro** [comment]
Hi,

I've added nested maps as well

(this commit has added the whitespace mess again, damn ) https://github.com/kokosro/clucy/commit/3822328adac9fea177e319959414af7543deff6d

**Comment by kokosro** [comment]
Hi,

This commit https://github.com/kokosro/clucy/commit/a2fffd10f104a2e946befcb71746915048007e51 enables array fields indexing and nested maps (transforming nested maps into dotted keys) (added tests for both of them).

Thank you

**Comment by kostafey** [comment]
It's very good in general. Let's fix a few items.
- Function `->value-or-vector` should be renamed to simpler `get-value-or-vector` since we have no `from` part here as in `from->to` cases.
- I think it's better to avoid use `doall` when you can use `dorun`. So, please replace it in 193 and 261 lines.
- Function `nested-map->dotted-key` should be renamed to `nested-key-map->dotted-key-map`. It's mach longer but more accuracy.
- The same story with `dotted-key->nested-map` => `dotted-key-map->nested-key-map`
- It's better to move all mentioned functions (`get-value-or-vector`, `nested-key-map->dotted-key-map`, `dotted-key-map->nested-key-map`) to `util.clj` file.
- Please fix code style at line 283 as follows:

``` clojure
(->value-or-vector a-map 
                   field-name
                   field-value)
```

... and prepare pull request.

**Comment by kokosro** [comment]
I've commited the changes and created pull request.

**Comment by kostafey** [comment]
Thank you.
